# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |d|
    d.has_ssh = true
    d.image = "markzaslavskiy/mooc:v1"

# Allowing testuser to auth by ssh using vagrant ssh -- -l testuser
    config.vm.provision "shell", inline: <<-EOC
      sudo mkdir /home/testuser/.ssh
      sudo cp /home/vagrant/.ssh/authorized_keys /home/testuser/.ssh/authorized_keys
      sudo chown testuser:root /home/testuser/.ssh/
      sudo chown testuser:testuser /home/testuser/.ssh/authorized_keys
      sudo chmod 700 /home/testuser/.ssh
      sudo chmod 600 /home/testuser/.ssh/authorized_keys
      sudo service ssh restart
    EOC

# Restricting ssh access using password
    config.vm.provision "shell", inline: <<-EOC
      sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
      sudo service ssh restart
    EOC
# Changing default passwords for vagrant and root
    config.vm.provision "shell", inline: <<-EOC
      password=`date +%s | sha256sum | base64 | head -c 32 ; echo`;echo "${password}\n${password}"| passwd 
      password=`date +%s | sha256sum | base64 | head -c 32 ; echo`;echo "${password}\n${password}"| passwd vagrant 
      password=`date +%s | sha256sum | base64 | head -c 32 ; echo`;echo "${password}\n${password}"| passwd testuser 
    EOC
# Giving access to /vagrant partition to testuser
    config.vm.provision "shell", inline: <<-EOC
      sudo chmod 777 /vagrant
    EOC
   
  end
end
